version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1
  serverless-framework: circleci/serverless-framework@2.0
jobs:
  deploy:
    executor: serverless-framework/default
    steps:
      - checkout
      - aws-cli/setup
      - serverless-framework/setup
      - run:
          name: move to folder backend
          command: cd course-04/project/c4-final-project-starter-code
      - run:
          command: serverless deploy -v
          name: deploy
workflows:
  deploy:
    jobs:
      - deploy
